# Generated by Django 5.2.1 on 2025-05-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
